articlesapp/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/22
@IDE: PyCharm
 
"""
from django.urls import path

from . import views

app_name = 'articlesapp'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('articles/', views.article_list, name='articles'),
    # path('show-article/<int:id>/', views.show_article, name='show_article'),
    path('show-article/<str:title>/', views.show_article, name='show_article'),
    path('articles/create/', views.article_create, name='article_create'),
    # 删除文章
    path('articles/delete/<str:title>/', views.article_delete, name='article_delete'),
    # 更新文章
    path('articles/update/<str:title>/', views.article_update, name='article_update'),
    path('articles/search/', views.search, name='search'),
]

comment/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/24
@IDE: PyCharm
 
"""



from django.urls import path

from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    # 新增代码，处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

homeapp/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/20
@IDE: PyCharm
 
"""

from django.urls import path, re_path

from . import views
# from homeapp import views

app_name = 'homeapp'
# 如果这里加了app_name.
# 那么在html中使用url解析时需要加homeapp:home

urlpatterns = [
    path('', views.home, name='home'),
    path('js/', views.js, name='js'),
    path('archives/', views.archives, name='archives'),
    re_path(r'^archives/[0-9]{4}/[0-9]*', views.archives_by_year_month, name='archives_by_year_month'),
    # re_path(r'^archives/[0-9]{4}/[0-9]+/$', views.archives_by_month, name='archives_by_month'),


    path('categories/', views.categories, name='categories'),
    # 这个路由其实可以用正则来写,但是在单独逆向解析url怎么办
    re_path(r'^categories/.*?', views.category_detail, name='category_detail'),
    # path('categories/Algorithm/', views.algorithm, name='Algorithm'),
    # path('categories/Deep_Learning/', views.deep_learning, name='Deep Learning'),
    # path('categories/Django/', views.django, name='Django'),
    # path('categories/Face_Recognition/', views.face_recognition, name='Face Recognition'),
    # path('categories/Linux/', views.linux, name='Linux'),
    # path('categories/Machine_Learning/', views.machine_learning, name='Machine Learning'),
    # path('categories/Object_Detection/', views.object_detection, name='Object Detection'),
    # path('categories/Other/', views.other, name='Other'),
    # path('categories/Python/', views.python, name='Python'),
    path('tags/', views.tags, name='tags'),
    re_path(r'^tags/.*?', views.tag_detail, name='tag_detail'),
    path('about/', views.about, name='about'),
]

resourceapp/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/30
@IDE: PyCharm
 
"""

from django.urls import path, re_path

from . import views
app_name = 'resourceapp'

urlpatterns = [
    path('downloads/', views.downloads, name='downloads'),
    # path('downloads/1706-transformer.pdf', views.preview, name='pre_pdf'),
    path('uploads/', views.uploads, name='uploads'),
    # re_path(r'downloads/图像分割论文.JPG/', views.downloads, name='3'),
    # re_path(r'downloads/数学之美第二版.pdf/', views.downloads, name='2'),
    # re_path(r'downloads/emoji.txt/', views.downloads, name='emoji.txt'),
    re_path(r'downloads/.*?', views.downloads, name='res'),
    # re_path(r'downloads/resources/.*?', views.preview, name='preview'),

]

sharewithyou/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.static import static


from sharewithyou import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # namespace 主要是为了防止不同应用的路由name属性相同，在反向解析时无法解析，
    # 也可以不设置，只要保持name不同就行
    path('', include('homeapp.urls', namespace='homeapp')),
    path('', include('articlesapp.urls', namespace='articlesapp')),
    path('', include('userprofile.urls', namespace='userprofile')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('resourceapp.urls', namespace='resourceapp')),

    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
# url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT})

userprofile/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/22
@IDE: PyCharm
 
"""
from django.urls import path

from . import views
# from homeapp import views

app_name = 'userprofile'
# 如果这里加了app_name.
# 那么在html中使用url解析时需要加homeapp:home

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

homeapp/models.py
from django.db import models

# Create your models here.

homeapp/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.db.models.functions import TruncMonth, TruncWeek, TruncYear, TruncDay
from django.db.models.functions import ExtractYear
from django.urls import path, re_path
import markdown

from articlesapp.models import ArticlePost, Category, TaggableManager

from articlesapp.views import article_list

MONTH = {'1': 'January', '2': 'February', '3': 'March', '4': 'April',
         '5': 'May', '6': 'June', '7': 'July', '8': 'August',
         '9': 'September', '10': 'October', '11': 'November', '12': 'December'}


# Create your views here.

def get_context(request):
    article_list = ArticlePost.objects.all()
    # 得到每个tag对应的文章数
    all_tags = ArticlePost.tags.all()
    # article_list = article_list.filter(tags__name__in=[tag])
    # all_articles = ArticlePost.objects.all()
    per_tag_articles = {}

    for tmp_tag in all_tags:
        # print('======427==', tmp_tag)
        tag_articles = article_list.filter(tags__name__in=[tmp_tag])
        per_tag_articles[str(tmp_tag)] = [len(tag_articles), tag_articles, ]

    per_tag_articles['other'] = []
    tmp_c = 0
    for art in article_list:
        if len(art.tags.all()) == 0:
            tmp_c += 1
            per_tag_articles['other'].append(art)
    per_tag_articles['other'].insert(0, tmp_c)
    # [tag:[文章数]]
    # context['tags_articles'] = per_tag_articles

    category = Category.objects.all().order_by('title')
    cate_articles = {}
    for tmp_cate in category:
        # print('====17', cate.title, cate.id)
        tmp_n = len(ArticlePost.objects.filter(column=tmp_cate.id))
        tmp_name = tmp_cate.title.replace(' ', '_')
        cate_articles[tmp_cate.title] = [tmp_cate, tmp_n, tmp_name]

    cate_num = len(Category.objects.all())
    tags_num = len(ArticlePost.tags.all())

    recent_articles = article_list[:5]
    num = len(article_list)

    search = request.GET.get('search', None)
    order = request.GET.get('order')
    # 用户搜索逻辑
    if search:
        article_list = ArticlePost.objects.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        # 将 search 参数重置为空
        search = ''
        article_list = ArticlePost.objects.all()
    order = 'normal'
    # 每页显示 6 篇文章
    paginator = Paginator(article_list, 6)
    # 获取 url 中的页码
    page = request.GET.get('page', 1)
    page_num = paginator.num_pages
    if int(page) > page_num:
        page = page_num
    elif int(page) <= 0:
        page = 1
    # 将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)
    info_by_month_years = recents_month_articles(request)

    context = {'cur_page_articles': None,  # 中间栏显示的内容 不同的页面不一样
               'num': num,  # 总的文章数
               'cate_num': cate_num,  # 总的目录数
               'tags_num': tags_num,  # 总的标签数
               'article_list': article_list,  # 所有的文章
               'order': order,  # 排序
               'search': search,  # 搜索关键字
               'recent_articles': recent_articles,  # 最近的5篇文章
               'category': category,  # 所有目录名字
               'cate_articles': cate_articles,  # 字典{column:[Queryset,文章数,url的名字}
               'info_by_month_years': info_by_month_years,
               'tags_articles': per_tag_articles,  # 字典{tagname:[文章数,Queryset]}
               }  # 保存每个类别有多少文章的列表

    return context

def archives_order_by_year(cur_articles):
    # all_articles = ArticlePost.objects.all().order_by('-created')
    all_articles = cur_articles
    years = {}
    month_years = {}
    for t in all_articles:
        if t.created.year not in years.keys():
            # years[t.created.year] = 1
            years[t.created.year] = [t, ]
        else:
            # years[t.created.year] += 1
            years[t.created.year].append(t)
        month_year = str(t.created.month) + ' ' + str(t.created.year)
        # print('====97=', t.created.month, t.created.year)
        if month_year not in month_years.keys():
            # month_years[month_year] = 1
            month_years[month_year] = [t, ]
        else:
            # month_years[month_year] += 1
            month_years[month_year].append(t)

    # 感觉应该在文章数据库里设置一个年份外键，月份外键

    # 返回一个字典：{years:[article1,article2]}
    return years, month_years


def get_recent_years_articles(request, a=2, y=4):
    all_articles = ArticlePost.objects.all().order_by('-created')
    articles_by_year, articles_by_month_years = archives_order_by_year(all_articles)
    res_art = []
    if len(articles_by_year) >= y:
        for key in list(articles_by_year.keys())[:y]:
            if len(articles_by_year[key]) >= a:
                res_art += articles_by_year[key][:a]
            else:
                res_art += articles_by_year[key]
    else:
        for key in articles_by_year.keys():
            if len(articles_by_year[key]) >= a:
                res_art += articles_by_year[key][:a]
            else:
                res_art += articles_by_year[key]

    return res_art


def recents_month_articles(request):
    """
    选出最近10个月的文章
    :param request:
    :return:
    """
    all_articles = ArticlePost.objects.all()
    articles_by_year, articles_by_month_years = archives_order_by_year(all_articles)

    tmp_articles_info = {}
    # print('=======141======', articles_by_month_years)
    i = 0
    # n = len(articles_by_month_years)
    for key in articles_by_month_years.keys():
        if i < 10:
            tmp = key.split(' ')
            # print('======', i, tmp)
            assert len(tmp) == 2
            tmp_month, tmp_year = tmp[0], tmp[1]
            # tmp_articles_info[MONTH[tmp_month]] = [tmp_month, tmp_year, len(articles_by_month_years[key])]
            tmp_articles_info[key] = [MONTH[tmp_month], tmp_month, tmp_year, len(articles_by_month_years[key])]
            i += 1

    # context['articles_by_month_years'] = tmp_articles
    # print('=======152======', tmp_articles_info)
    tmp_list = sorted(tmp_articles_info.items(), key=lambda x: (int(x[1][2]), int(x[1][1])), reverse=True)
    res = {}
    for item in tmp_list:
        res[item[0]] = item[1]
    # print('======166=====',res)
    return res


def filter_by_request(request):
    """
    返回过滤后的所有文章
    :param request:
    :return:
    """

    all_articles = ArticlePost.objects.all()
    articles_by_year, articles_by_month_years = archives_order_by_year(all_articles)

    # 显示每年的最新的5篇文章，
    # 两种case.第一种某年不止5篇，第二种某年小于5篇
    # {years: [article1, article2]}
    # 得到每年的全部文章
    tmp_articles = []
    # 取出每年的5篇文章，不足的年份全取
    for y, art in articles_by_year.items():
        if len(art) > 2:
            tmp_articles += art[:2]
        else:
            tmp_articles += art
    # 将取出来的进行分页
    paginator = Paginator(tmp_articles, 8)
    # 获取 url 中的页码
    page = request.GET.get('page', 1)
    page_num = paginator.num_pages
    if int(page) > page_num:
        page = page_num
    elif int(page) <= 0:
        page = 1
    # 得到当前页的文章数
    cur_articles = paginator.get_page(page)

    page_articles = cur_articles
    cur_articles_queryset = []
    for i in page_articles:
        cur_articles_queryset.append(i)
    # 得到当前页的年份:文章数
    cur_articles_by_year, cur_articles_by_month_years = archives_order_by_year(cur_articles_queryset)
    context = get_context(request)
    context['cur_articles_by_year'] = cur_articles_by_year
    context['cur_articles_by_month_years'] = cur_articles_by_month_years
    context['articles_by_year'] = articles_by_year
    context['articles_by_month_years'] = articles_by_month_years
    context['page_articles'] = page_articles
    context['page_num'] = page_num
    context['info_by_month_years'] = recents_month_articles(request)
    return context


def archives(request):
    # 返回字典：{years: [article1, article2]}
    # all_articles = ArticlePost.objects.all()
    # TODO 显示每年的最新的2篇文章，一页显示4年
    context = filter_by_request(request)
    search = request.GET.get('search', None)
    if search:
        # TODO 如果有search，可以在所有文章或者某一年或者某一年的某一个月搜索
        all_articles = ArticlePost.objects.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
        cur_page_articles, _ = get_paginator(request, all_articles, 6)
        context['cur_page_articles'] = cur_page_articles
        return render(request, "homeapp/index.html", context)
    else:
        # print('=====',context)
        return render(request, "homeapp/archives.html", context)


def archives_by_year_month(request):
    url = request.path.strip('/').split('/')
    all_articles = ArticlePost.objects.all()
    articles_by_year, articles_by_month_years = archives_order_by_year(all_articles)
    context = get_context(request)
    # info_by_month_years = recents_month_articles(request)
    cur_year = None
    cur_month = None
    tmp_articles = None
    if len(url) == 2:
        cur_year = url[1]
        tmp_articles = articles_by_year.get(int(cur_year), None)
        cur_month = ''
    elif len(url) == 3:
        cur_year = url[1]
        cur_month = int(url[2])
        context['cur_month'] = str(url[2])
        if cur_month <= 0:
            cur_month = 1
        elif cur_month > 12:
            cur_month = 12
        tmp_articles = articles_by_month_years.get(str(cur_month)+' '+str(cur_year), None)
        # print('=====258=====', tmp_articles)
    if tmp_articles is None:
        return Http404('当前未发表文章，请看看其他的吧')
    cur_page_articles, page_num = get_paginator(request, tmp_articles, 1)
    # print('=====262===', cur_page_articles)
    # paginator = Paginator(tmp_articles, 10)
    # # 获取 url 中的页码
    # page = request.GET.get('page', 1)
    # page_num = paginator.num_pages
    # if int(page) > page_num:
    #     page = page_num
    # elif int(page) <= 0:
    #     page = 1
    # # 得到当前页的文章数
    # cur_articles = paginator.get_page(page)
    # page_articles = cur_articles

templates/homeapp/download.html
{% extends 'base.html' %}
{% load static %}


{% block left_column %}
    <div class="column column-left is-4-tablet is-4-desktop is-3-widescreen  order-1">
        <div class="card widget" data-type="profile"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <nav class="level">
                    <div class="level-item has-text-centered flex-shrink-1">
                        <div>
                            <a href="{% url 'userprofile:login' %}">
                                <figure class="image is-128x180 mx-auto mb-2">
                                    <img class="avatar" src="{% static 'images/logos/logo.svg' %}"
                                         alt="PPOffice"></figure>
                            </a>
                            <p class="title is-size-4 is-block" style="line-height:inherit;">Week · Study</p>
                            <p class="is-size-6 is-block">Developer</p>
                            <p class="is-size-6 is-flex justify-content-center"><i
                                    class="fas fa-map-marker-alt mr-1"></i><span>Earth, Solar System</span></p></div>
                    </div>
                </nav>
                <nav class="level is-mobile">
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Posts</p><a href="{% url 'homeapp:archives' %}">
                            <p class="title"> {{ num }}</p>
                        </a></div>
                    </div>
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Categories</p><a href="{% url 'homeapp:categories' %}">
                            <p class="title">{{ cate_num }}</p></a></div>
                    </div>
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Tags</p><a href="{% url 'homeapp:tags' %}">
                            <p class="title">{{ tags_num }}</p></a>
                        </div>
                    </div>
                </nav>
                {% include 'connectblock.html' %}
            </div>
        </div>
        {% include 'linksblock.html' %}
         <div class="card widget" data-type="categories"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <div class="menu"><h3 class="menu-label">Categories</h3>
                    <ul class="menu-list">
                        {% for tmp_col,tmp_art in cate_articles.items %}
                        <li><a class="level is-mobile" href="/categories/{{ tmp_art.2 }}"><span
                                class="level-start"><span class="level-item">{{ tmp_col }}</span></span><span
                                class="level-end"><span class="level-item tag">{{ tmp_art.1 }}</span></span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {# 在移动端使用的样式#}
{#        {% include 'unkownblock.html' %}#}
    </div>
{% endblock left_column %}


{% block mid_column %}
    <div class="column order-2 column-main is-8-tablet is-8-desktop is-6-widescreen">
        <div class="card widget" data-type="tags"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <div class="menu">
                    <h3 class="menu-label "><a href="{% url 'resourceapp:downloads' %}">Resources</a>
                        &nbsp;&nbsp;&nbsp;<a href="{% url 'resourceapp:uploads' %}">Upload</a></h3><hr>

                    <ul class="menu-list">
                        <li>
                            {% for res in resources %}
                                <a class="level is-mobile" href="{{ res.url2 }}">
                                    <span class="level-start">
                                        <span class="level-item">{{ res.name }}</span>
                                    </span>
                                    <span class="level-end">
                                        <span class="level-item tag">{{ res.download_count }}</span>
                                    </span>
                                </a>
                            {% endfor %}

                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock mid_column %}

{% block right-column %}
    <div class="column column-right is-4-tablet is-4-desktop is-3-widescreen is-hidden-touch is-hidden-desktop-only order-3">
        <div class="card widget" data-type="recent-posts"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content"><h3 class="menu-label">Recents</h3>
                {% for article in recent_articles %}
                    <article class="media">
                         {% if article.avatar_svg %}
                            <figure class="media-left">
                                <a class="image" href="{% url 'articlesapp:show_article' article.title %}">
                                    <img src="{{ article.avatar_svg.url }}"
                                         alt="{{ article.title }}"></a>
                            </figure>
                        {% endif %}
                        <div class="media-content">
                            <p class="title"><a href="{% url 'articlesapp:show_article' article.title %}">{{ article.title }}</a>
                            </p>
                            <p class="date">{{ article.author }} </p>

                            <p class="date">{{ article.created|date:"Y-m-d"}} </p>
                        </div>
                    </article>
                {% endfor %}
            </div>
        </div>
        <div class="card widget" data-type="archives"
                 style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
                <div class="card-content">
                    <div class="menu"><h3 class="menu-label">Archives</h3>
                        <ul class="menu-list">
                            {% for month_year,art in info_by_month_years.items %}
                                <li>
                                    <a class="level is-mobile" href="/archives/{{ art.2 }}/{{ art.1 }}">
                                        <span class="level-start">
                                            <span class="level-item">{{ art.0 }} {{ art.2 }}</span>
                                        </span>
                                        <span class="level-end">
                                            <span class="level-item tag">{{ art.3 }}</span>
                                        </span>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

        <div class="card widget" data-type="tags"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <div class="menu"><h3 class="menu-label">Tags</h3>
                    <div class="field is-grouped is-grouped-multiline">
                        {% for tag_name,tag_articles in tags_articles.items %}
                            <div class="control">
                                <a class="tags has-addons" href="/tags/{{ tag_name }}">
                                    <span class="tag">{{ tag_name }}</span>
                                    <span class="tag">{{ tag_articles.0 }}</span>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock right-column %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock footer %}

{% block search %}
    <div class="searchbox">
        <div class="searchbox-container">
            <div class="searchbox-header">
                <div class="searchbox-input-container">
                    <form method="get" >
                        <input class="searchbox-input" name="search" type="text" placeholder="Type something..." >
                    </form>
                </div>
                <a class="searchbox-close" href="javascript:;">×</a></div>
                <div class="searchbox-body">
                    <section class="searchbox-result-section">
                        <header>Posts</header>
                        {% for article in article_list|slice:":5" %}
                        <a class="searchbox-result-item"
                           href="{% url 'articlesapp:show_article' article.title %}">
                            <span class="searchbox-result-icon"> <i class="fa fa-file"></i></span>
                            <span class="searchbox-result-content">
                                <span class="searchbox-result-title"> {{ article.title }}</span>
                                <span class="searchbox-result-title">AUTHOR: {{ article.author|upper }}&nbsp;&nbsp;
                                    POSTED:{{ article.created|date:"Y-m-d" }}</span>
                                <span class="searchbox-result-preview">{{ article.body|safe|slice:'100' }}</span>
                            </span>
                        </a>

                        {% endfor %}
                    </section>

                    <section class="searchbox-result-section">
                        <header>Categories</header>
                         {% for cate_key, article_info in  cate_articles.items %}
                            <a class="searchbox-result-item" href="/categories/{{ article_info.2 }}">
                                <span class="searchbox-result-icon"><i class="fa fa-folder"></i></span>
                                    <span class="searchbox-result-content">
                                        <span class="searchbox-result-title">{{ cate_key }}</span>
                                    </span>
                            </a>
                         {% endfor %}
                    </section>
                    <section class="searchbox-result-section">
                        <header>Tags</header>
                        {% for tag_name,article_info in tags_articles.items %}
                            <a class="searchbox-result-item" href="/tags/{{ tag_name }}">
                                <span class="searchbox-result-icon"><i class="fa fa-tag"></i></span>
                                <span class="searchbox-result-content">
                                    <span class="searchbox-result-title">{{ tag_name }}
                                    </span>
                                </span>
                            </a>
                        {% endfor %}
                    </section>
                </div>
            </div>
        </div>
    </div>
{% endblock search %}