articlesapp/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/22
@IDE: PyCharm
 
"""
from django.urls import path

from . import views

app_name = 'articlesapp'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('articles/', views.article_list, name='articles'),
    # path('show-article/<int:id>/', views.show_article, name='show_article'),
    path('show-article/<str:title>/', views.show_article, name='show_article'),
    path('articles/create/', views.article_create, name='article_create'),
    # 删除文章
    path('articles/delete/<str:title>/', views.article_delete, name='article_delete'),
    # 更新文章
    path('articles/update/<str:title>/', views.article_update, name='article_update'),
    path('articles/search/', views.search, name='search'),
]

comment/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/24
@IDE: PyCharm
 
"""



from django.urls import path

from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    # 新增代码，处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

homeapp/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/20
@IDE: PyCharm
 
"""

from django.urls import path, re_path

from . import views
# from homeapp import views

app_name = 'homeapp'
# 如果这里加了app_name.
# 那么在html中使用url解析时需要加homeapp:home

urlpatterns = [
    path('', views.home, name='home'),
    path('js/', views.js, name='js'),
    path('archives/', views.archives, name='archives'),
    re_path(r'^archives/[0-9]{4}/[0-9]*', views.archives_by_year_month, name='archives_by_year_month'),
    # re_path(r'^archives/[0-9]{4}/[0-9]+/$', views.archives_by_month, name='archives_by_month'),


    path('categories/', views.categories, name='categories'),
    # 这个路由其实可以用正则来写,但是在单独逆向解析url怎么办
    re_path(r'^categories/.*?', views.category_detail, name='category_detail'),
    # path('categories/Algorithm/', views.algorithm, name='Algorithm'),
    # path('categories/Deep_Learning/', views.deep_learning, name='Deep Learning'),
    # path('categories/Django/', views.django, name='Django'),
    # path('categories/Face_Recognition/', views.face_recognition, name='Face Recognition'),
    # path('categories/Linux/', views.linux, name='Linux'),
    # path('categories/Machine_Learning/', views.machine_learning, name='Machine Learning'),
    # path('categories/Object_Detection/', views.object_detection, name='Object Detection'),
    # path('categories/Other/', views.other, name='Other'),
    # path('categories/Python/', views.python, name='Python'),
    path('tags/', views.tags, name='tags'),
    re_path(r'^tags/.*?', views.tag_detail, name='tag_detail'),
    path('about/', views.about, name='about'),
]

resourceapp/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/30
@IDE: PyCharm
 
"""

from django.urls import path, re_path

from . import views
app_name = 'resourceapp'

urlpatterns = [
    path('downloads/', views.downloads, name='downloads'),
    # path('downloads/1706-transformer.pdf', views.preview, name='pre_pdf'),
    path('uploads/', views.uploads, name='uploads'),
    # re_path(r'downloads/图像分割论文.JPG/', views.downloads, name='3'),
    # re_path(r'downloads/数学之美第二版.pdf/', views.downloads, name='2'),
    # re_path(r'downloads/emoji.txt/', views.downloads, name='emoji.txt'),
    re_path(r'downloads/.*?', views.downloads, name='res'),
    # re_path(r'downloads/resources/.*?', views.preview, name='preview'),

]

sharewithyou/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.static import static


from sharewithyou import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # namespace 主要是为了防止不同应用的路由name属性相同，在反向解析时无法解析，
    # 也可以不设置，只要保持name不同就行
    path('', include('homeapp.urls', namespace='homeapp')),
    path('', include('articlesapp.urls', namespace='articlesapp')),
    path('', include('userprofile.urls', namespace='userprofile')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('resourceapp.urls', namespace='resourceapp')),

    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
# url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT})

userprofile/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/22
@IDE: PyCharm
 
"""
from django.urls import path

from . import views
# from homeapp import views

app_name = 'userprofile'
# 如果这里加了app_name.
# 那么在html中使用url解析时需要加homeapp:home

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

templates/archivesblock.html
<div class="card widget" data-type="archives"
     style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
    <div class="card-content">
        <div class="menu"><h3 class="menu-label">Archives</h3>
            <ul class="menu-list">
                {% for month,art in articles_by_month_years.items %}
                    <li>
                        <a class="level is-mobile" href="/archives/{{ art.1 }}/{{ art.0 }}">
                        <span class="level-start">
                            <span class="level-item">{{ month }} {{ art.1 }}</span>
                        </span>
                            <span class="level-end">
                            <span class="level-item tag">{{ art.2 }}</span>
                        </span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/base.html
{% load static %}



<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>share</title>
    <link rel="SHORTCUT ICON"  href="{% static 'images/logos/logo.svg' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css-theme/icarus/style/default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static "fontawesome/css/all.min.css" %}">
    <link rel="stylesheet" href="{% static 'md_css/colorful.css' %}">
{#    <link rel="stylesheet" href="{% static 'http_use/http_use.fontawesome.com_releases_v5.15.2_css_all.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'http_use/http_cdn.jsdelivr.net_npm_highlight.js_9.12.0_styles_atom-one-light.css' %}">#}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;600&amp;family=Source+Code+Pro">
    <script type="text/javascript" async=""
            src="{% static 'http_cdn_js/http_www.google-analytics.com_analytics.js' %}"></script>
    <style>body > .footer, body > .navbar, body > .section {
        opacity: 0
    }
    </style>

</head>


<body class="is-3-column  pace-done">

<div role="dialog" aria-live="polite" aria-label="cookieconsent" aria-describedby="cookieconsent:desc"
     class="cc-window cc-floating cc-type-info cc-theme-edgeless cc-bottom cc-left cc-color-override--1762072787 cc-invisible"
     style="display: none;"><!--googleoff: all--><span id="cookieconsent:desc" class="cc-message">This website uses cookies to improve your experience. <a
        aria-label="learn more about cookies" role="button" tabindex="0" class="cc-link"
        href="https://www.cookiesandyou.com/" rel="noopener noreferrer nofollow" target="_blank">Learn more</a></span>
    <div class="cc-compliance"><a aria-label="dismiss cookie message" role="button" tabindex="0"
                                  class="cc-btn cc-dismiss">Got it!</a></div><!--googleon: all-->
</div>
<div class="pace  pace-inactive">
    <div class="pace-progress" data-progress-text="100%" data-progress="99"
         style="transform: translate3d(100%, 0px, 0px);">
        <div class="pace-progress-inner"></div>
    </div>
    <div class="pace-activity"></div>
</div>

<nav class="navbar navbar-main"
     style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform: translateY(0px);">

    <div class="container">
        <div class="navbar-brand justify-content-center" style="float: left">
            <a class="navbar-item navbar-logo" href="{% url 'homeapp:home' %}">
                <img src="{% static 'images/logos/logo.svg' %}" alt="Icarus" height="28"></a>
        </div>
        <div class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'homeapp:home' %}"> Home</a>
                <a class="navbar-item" href="{% url 'homeapp:categories' %}">Categories</a>
                <a class="navbar-item" href="{% url 'homeapp:archives' %}">Archives</a>
                <a class="navbar-item" href="{% url 'homeapp:tags' %}">Tag</a>
                <a class="navbar-item" href="{% url 'homeapp:about' %}">About</a>
                <a class="navbar-item" href="{% url 'resourceapp:downloads' %}">Downloads</a>
            </div>
            <div class="navbar-end">

                <a class="navbar-item" target="_blank" rel="noopener" title="Discuss on Github"
                   href="https://github.com/weekstudy/sharewithyou/discussions">
                    <i class="fas fa-comments"></i>
                </a>

                <a class="navbar-item" target="_blank" rel="noopener" title="Dowaload on Github"
                   href="https://github.com/weekstudy/sharewithyou">
                    <i class="fab fa-github"></i>
                </a>

                <a class="navbar-item search" title="Search" href="{% url 'articlesapp:search' %}">
                    <i class="fas fa-search" ></i>

                </a>
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <a class="navbar-item" target="_blank" rel="noopener" title="New Blog"
                       href="{% url 'articlesapp:article_create' %}">
                        <i class="fas fa-file"></i>
                    </a>
                    <a class="navbar-item" target="_blank" rel="noopener" title="Sign out "
                       href="{% url "userprofile:logout" %}">
                        <i class="fas fa-user" style="color: springgreen"></i>
                    </a>
                {% else %}
                    <a class="navbar-item" target="_blank" rel="noopener" title="Sign in "
                       href="{% url 'userprofile:login' %}">
                        <i class="fas fa-user"></i>
                    </a>

                {% endif %}

            </div>
        </div>
    </div>
</nav>

<section>
    {#个人简介#}
    <div class="container">
        <div class="columns">
            {% block left_column %}
            {% endblock left_column %}

            {#文章内容#}
            {% block mid_column %}
            {% endblock mid_column %}
            {#最近文章#}
            {% block right-column %}
            {% endblock right-column %}
            {#归档#}
        </div>
    </div>

</section>

{% block footer %}
{% endblock footer %}

<script src="{% static 'http_cdn_js/http_cdn.jsdelivr.net_npm_jquery_3.3.1_dist_jquery.js' %}"></script>
<script src="{% static 'http_cdn_js/http_cdn.jsdelivr.net_npm_moment_2.22.2_min_moment-with-locales.js' %}"></script>
<script src="{% static 'http_cdn_js/http_cdn.jsdelivr.net_npm_clipboard_2.0.4_dist_clipboard.js' %}"
        defer=""></script>
<script>moment.locale("en");</script>

<script>var IcarusThemeSettings = {
    article: {
        highlight: {
            clipboard: true,
            fold: 'unfolded'
        }
    }
};</script>
<script src="{% static 'js/js/column.js' %}"></script>
<script src="{% static 'js/js/animation.js' %}"></script>

{#TODO 返回顶部按钮#}
<a id="back-to-top" title="Back to top" href="javascript:;" class="card has-text-centered rise-up fade-in"
   style="left: 1103.75px; width: 64px; bottom: 20px;">
    <i class="fas fa-chevron-up"></i>
</a>
<script src="{% static 'js/js/back_to_top.js' %}" defer=""></script>


<!--!-->
<!--!-->
<!--!-->

<script src="{% static 'http_cdn_js/http_cdn.jsdelivr.net_npm_cookieconsent_3.1.1_build_cookieconsent.min.js' %}"
        defer></script>
<script>window.addEventListener("load", () => {
    window.cookieconsent.initialise({
        type: "info",
        theme: "edgeless",
        static: false,
        position: "bottom-left",
        content: {
            message: "This website uses cookies to improve your experience.",
            dismiss: "Got it!",
            allow: "Allow cookies",
            deny: "Decline",
            link: "Learn more",
            policy: "Cookie Policy",
            href: "https://www.cookiesandyou.com/",
        },
        palette: {
            popup: {
                background: "#edeff5",
                text: "#838391"
            },
            button: {
                background: "#4b81e8"
            },
        },
    });
});</script>
<script src="{% static 'http_cdn_js/http_cdn.jsdelivr.net_npm_lightgallery_1.6.8_dist_js_lightgallery.js' %}"
        defer></script>
<script src="{% static 'http_cdn_js/http_cdn.jsdelivr.net_npm_justifiedGallery_3.7.0_dist_js_jquery.justifiedGallery.js' %}"
        defer></script>
<script>window.addEventListener("load", () => {
    if (typeof $.fn.lightGallery === 'function') {
        $('.article').lightGallery({selector: '.gallery-item'});
    }
    if (typeof $.fn.justifiedGallery === 'function') {
        if ($('.justified-gallery > p > .gallery-item').length) {
            $('.justified-gallery > p > .gallery-item').unwrap();
        }
        $('.justified-gallery').justifiedGallery();
    }
});</script>
<!--!-->
<!--!-->
{#<div id="outdated"><h6>Your browser is out-of-date!</h6>#}
{#    <p>Update your browser to view this website correctly.&amp;npsb;#}
{#        <a id="btnUpdateBrowser" href="http://outdatedbrowser.com/">Update my#}
{#            browser now </a></p>#}
{#    <p class="last"><a href="#" id="btnCloseUpdateBrowser" title="Close">×</a></p></div>#}
<script src="{% static 'http_cdn_js/http_cdn.jsdelivr.net_npm_outdatedbrowser_1.1.5_outdatedbrowser_outdatedbrowser.js' %}"
        defer></script>
<script>window.addEventListener("load", function () {
    outdatedBrowser({
        bgColor: '#f25648',
        color: '#ffffff',
        lowerThan: 'object-fit' // display on IE11 or below
    });
});</script><!--!--><!--!--><!--!-->
<script src="{% static 'js/js/main.js' %}" defer></script>

{% block search %}
{% endblock search %}

<script src="{% static 'js/js/insight.js' %}" defer></script>

<script>
    // 这是content.json文件里面其实是所有文章
    document.addEventListener('DOMContentLoaded', function () {
    loadInsight({"contentUrl": ""}, {
        "hint": "Type something...",
        "untitled": "(Untitled)",
        "posts": "Posts",
        "pages": "Pages",
        "categories": "Categories",
        "tags": "Tags"
    });
});
</script>



</body>
</html>

templates/categoryblock.html
{% load static %}

<div class="card widget" data-type="categories"
     style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
    <div class="card-content">
        <div class="menu"><h3 class="menu-label">Categories</h3>
            <ul class="menu-list">
                <li><a class="level is-mobile" href="{% url 'homeapp:Algorithm' %}"><span
                        class="level-start"><span class="level-item">Algorithm</span></span><span
                        class="level-end"><span class="level-item tag">4</span></span></a></li>
                <li><a class="level is-mobile" href="/hexo-theme-icarus/categories/Plugins/"><span
                        class="level-start"><span class="level-item">Plugins</span></span><span
                        class="level-end"><span class="level-item tag">12</span></span></a>
                    </ul>
                </li>
                <li><a class="level is-mobile" href="/hexo-theme-icarus/categories/Widgets/"><span
                        class="level-start"><span class="level-item">Widgets</span></span><span
                        class="level-end"><span class="level-item tag">2</span></span></a></li>
            </ul>
        </div>
    </div>
</div>

templates/connectblock.html
{% load static %}

<div class="level"><a class="level-item button is-primary is-rounded" href="https://github.com/weekstudy"
                      target="_blank" rel="noopener">Follow</a></div>
<div class="level is-mobile is-multiline">
    <a class="level-item button is-transparent is-marginless" target="_blank" rel="noopener" title="Github"
       href="https://github.com/weekstudy"><i class="fab fa-github fa-2x"></i>
    </a>
    <a class="level-item button is-transparent is-marginless" target="_blank" rel="noopener"
       title="wechat" href="{% static 'images/weixin.jpg' %}"><i class="fab fa-weixin fa-2x"></i>
    </a>
    <a class="level-item button is-transparent" target="_blank" rel="noopener"
       title="weibo" href="https://weibo.com/u/5034013030"><i class="fab fa-weibo fa-2x"></i> </a>
    <a title="Dribbble" href="mailto:zhouqiangweek@foxmail.com"><i class="fa fa-envelope fa-2x" style="color:grey"></i></a>
    <a class="level-item button is-transparent is-marginless" target="_blank" rel="noopener"
       title="RSS" href="{% url 'homeapp:home' %}"><i class="fas fa-rss fa-2x"></i>
    </a>
</div>

templates/footer.html
{% load static %}

<footer class="footer" style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1;">
    <div class="container">
        <div class="level">
            <div class="level-start">
                <a class="footer-logo is-block mb-2" href="/">
                    <img src="{% static "images/logos/logo.svg" %}" alt="Icarus" height="40">

                </a>

                <p class="is-size-7">
                    <span>Copyright © 2021 ZBlog</span>
                    &nbsp;&nbsp;Powered by
                    <a href="https://hexo.io/" target="_blank" rel="noopener">Hexo</a>
                    &nbsp;&amp;&nbsp;<a href="https://github.com/weekstudy" target="_blank"
                                        rel="noopener">Zhou</a>
                </p>
                <p class="center">
                    <span>备案号：</span>
                        <a href="http://beian.miit.gov.cn/">渝ICP备2022001703号</a>
                </p>

            </div>
            <div class="level-end">
                <div class="field has-addons">
                    <p class="control">
                        <a class="button is-transparent is-large" target="_blank" rel="noopener"
                           title="Creative Commons" href="https://creativecommons.org/">
                            <i class="fab fa-creative-commons"></i>
                        </a>
                    </p>
                    <p class="control">
                        <a class="button is-transparent is-large" target="_blank" rel="noopener"
                           title="Discuss on GitHub" href="https://github.com/weekstudy/sharewithyou/discussions">
                            <i class="fas fa-comments"></i>
                        </a>
                    </p>
                    <p class="control">
                        <a class="button is-transparent is-large" target="_blank" rel="noopener"
                           title="Download on GitHub" href="https://github.com/weekstudy">
                            <i class="fab fa-github"></i>
                        </a>
                    </p>

                </div>
            </div>
        </div>
    </div>


</footer>

templates/header.html
{% load static %}


<nav class="navbar navbar-main" style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform: translateY(0px);">

    <div class="container">
        <div class="navbar-brand justify-content-center" style="float: left">
            <a class="navbar-item navbar-logo" href=""><img src="/static/images/logo.JPG" alt="Icarus" height="28"></a>
        </div>
        <div class="navbar-menu">
            <div class="navbar-start">
{#                <a class="navbar-item is-active" href="{% url 'homeapp:home' %}"> Home</a>#}
                <a class="navbar-item" href="{% url 'homeapp:home' %}"> Home</a>
                <a class="navbar-item" href="{% url 'homeapp:categories' %}">Categories</a>
                <a class="navbar-item" href="{% url 'homeapp:archives' %}">Archives</a>
                <a class="navbar-item" href="{% url 'homeapp:tags' %}">Tag</a>
                <a class="navbar-item" href="{% url 'homeapp:about' %}">About</a>
            </div>
            <div class="navbar-end">

                <a class="navbar-item" target="_blank" rel="noopener" title="Discuss on Github" href="https://github.com/ppoffice/hexo-theme-icarus/discussions">
                    <i class="fas fa-comments"></i>
                </a>

                <a class="navbar-item" target="_blank" rel="noopener" title="Dowaload on Github" href="https://github.com/ppoffice/hexo-theme-icarus">
                    <i class="fab fa-github"></i>
                </a>

                <a class="navbar-item search" title="Search" href="">
                    <i class="fas fa-search"></i>
                </a>
                <a class="navbar-item" target="_blank" rel="noopener" title="Sign in " href="{% url 'userprofile:login'%}">
                    <i class="fas fa-user" ></i>
                </a>

            </div>
        </div>
    </div>
</nav>

templates/linksblock.html
{% load static %}

<div class="card widget" data-type="links"
         style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
        <div class="card-content">
            <div class="menu"><h3 class="menu-label">Links</h3>
                <ul class="menu-list">
                    <li><a class="level is-mobile" href="https://hexo.io" target="_blank" rel="noopener"><span
                            class="level-left"><span class="level-item">Hexo</span></span><span class="level-right"><span
                            class="level-item tag">hexo.io</span></span></a></li>
                    <li><a class="level is-mobile" href="https://bulma.io" target="_blank" rel="noopener"><span
                            class="level-left"><span class="level-item">Bulma</span></span><span
                            class="level-right"><span class="level-item tag">bulma.io</span></span></a></li>
                </ul>
            </div>
        </div>
    </div>

templates/profile.html
{% load static %}

<div class="card widget" data-type="profile"
     style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
    <div class="card-content">
        <nav class="level">
            <div class="level-item has-text-centered flex-shrink-1">
                <div>
                    <a href="{% url 'userprofile:login' %}">
                        <figure class="image is-128x128 mx-auto mb-2">
                            <img class="avatar" src="{% static 'images/logo.JPG' %}"
                                 alt="PPOffice"></figure>
                    </a>
                    <p class="title is-size-4 is-block" style="line-height:inherit;">Janue · ZHOU</p>
                    <p class="is-size-6 is-block">Developer</p>
                    <p class="is-size-6 is-flex justify-content-center"><i
                            class="fas fa-map-marker-alt mr-1"></i><span>Earth, Solar System</span></p></div>
            </div>
        </nav>
        <nav class="level is-mobile">
            <div class="level-item has-text-centered is-marginless">
                <div><p class="heading">Posts</p><a href="{% url 'homeapp:archives' %}"><p class="title">39TODO</p>
                </a></div>
            </div>
            <div class="level-item has-text-centered is-marginless">
                <div><p class="heading">Categories</p><a href="{% url 'homeapp:categories' %}"><p class="title">
                    9</p></a></div>
            </div>
            <div class="level-item has-text-centered is-marginless">
                <div><p class="heading">Tags</p><a href="{% url 'homeapp:tags' %}"><p class="title">4</p></a>
                </div>
            </div>
        </nav>
        {% include 'connectblock.html' %}
    </div>
</div>

templates/recentsblock.html
{% load static %}

<div class="card widget" data-type="recent-posts"
     style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
    <div class="card-content"><h3 class="menu-label">Recents</h3>
        <article class="media">
            <figure class="media-left">
                <a class="image" href="{% url 'articlesapp:show_article' 3 %}">
                    <img src="{% static 'images/cover_imgs/vector_landscape_1.svg' %}"
                         alt="Getting Started with Icarus"></a></figure>
            <div class="media-content">
                <p class="date">
                    <time datetime="2021-12-21T00:00:00.000Z">2021-12-21</time>
                </p>
                <p class="title"><a href="/hexo-theme-icarus/uncategorized/getting-started-with-icarus/">Getting
                    Started with Icarus</a></p></div>
        </article>
        <article class="media">
            <figure class="media-left">
                <a class="image" href="/hexo-theme-icarus/Configuration/icarus-user-guide-configuring-the-theme/"><img
                    src="{% static 'images/cover_imgs/vector_landscape_2.svg' %}"
                    alt="Icarus User Guide - Configuring the Theme"></a></figure>
            <div class="media-content">
                <p class="date">
                    <time datetime="2020-03-01T00:00:00.000Z">2020-03-01</time>
                </p>
                <p class="title"><a
                        href="/hexo-theme-icarus/Configuration/icarus-user-guide-configuring-the-theme/">Icarus
                    User Guide - Configuring the Theme</a></p>
                <p class="categories"><a href="/hexo-theme-icarus/categories/Configuration/">Configuration</a>
                </p></div>
        </article>
        <article class="media">
            <figure class="media-left"><a class="image" href="/hexo-theme-icarus/uncategorized/faq/"><img
                    src="{% static 'images/cover_imgs/vector_landscape_3.svg' %}" alt="FAQ"></a></figure>
            <div class="media-content">
                <p class="date">
                    <time datetime="2020-02-02T00:00:00.000Z">2020-02-02</time>
                </p>
                <p class="title"><a href="/hexo-theme-icarus/uncategorized/faq/">FAQ</a></p></div>
        </article>
        <article class="media">
            <figure class="media-left"><a class="image"
                                          href="/hexo-theme-icarus/uncategorized/cyberpunk-theme-variant/"><img
                    src="/hexo-theme-icarus/gallery/covers/CP77-KV-en.jpg" alt="Cyberpunk Theme Variant"></a>
            </figure>
            <div class="media-content">
                <p class="date">
                    <time datetime="2020-02-01T00:00:00.000Z">2020-02-01</time>
                </p>
                <p class="title"><a href="/hexo-theme-icarus/uncategorized/cyberpunk-theme-variant/">Cyberpunk
                    Theme Variant</a></p></div>
        </article>
        <article class="media">
            <div class="media-content">
                <p class="date">
                    <time datetime="2020-01-01T00:00:00.000Z">2020-01-01</time>
                </p>
                <p class="title"><a href="/hexo-theme-icarus/uncategorized/upgrade-guide/">Upgrade Guide</a></p>
            </div>
        </article>
    </div>
</div>

templates/tagsblock.html
<div class="card widget" data-type="tags"
     style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
    <div class="card-content">
        <div class="menu"><h3 class="menu-label">Tags</h3>
            <div class="field is-grouped is-grouped-multiline">
                <div class="control"><a class="tags has-addons" href="/hexo-theme-icarus/tags/Demo/"><span
                        class="tag">Demo</span><span class="tag">15</span></a></div>
                <div class="control"><a class="tags has-addons" href="/hexo-theme-icarus/tags/Getting-Started/"><span
                        class="tag">Getting Started</span><span class="tag">4</span></a></div>
                <div class="control"><a class="tags has-addons"
                                        href="/hexo-theme-icarus/tags/Icarus-User-Guide/"><span class="tag">Icarus User Guide</span><span
                        class="tag">12</span></a></div>
                <div class="control"><a class="tags has-addons"
                                        href="/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/"><span
                        class="tag">Icarus用户指南</span><span class="tag">12</span></a></div>
            </div>
        </div>
    </div>
</div>