articlesapp/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/22
@IDE: PyCharm
 
"""
from django.urls import path

from . import views

app_name = 'articlesapp'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('articles/', views.article_list, name='articles'),
    # path('show-article/<int:id>/', views.show_article, name='show_article'),
    path('show-article/<str:title>/', views.show_article, name='show_article'),
    path('articles/create/', views.article_create, name='article_create'),
    # 删除文章
    path('articles/delete/<str:title>/', views.article_delete, name='article_delete'),
    # 更新文章
    path('articles/update/<str:title>/', views.article_update, name='article_update'),
    path('articles/search/', views.search, name='search'),
]

comment/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/24
@IDE: PyCharm
 
"""



from django.urls import path

from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    # 新增代码，处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

homeapp/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/20
@IDE: PyCharm
 
"""

from django.urls import path, re_path

from . import views
# from homeapp import views

app_name = 'homeapp'
# 如果这里加了app_name.
# 那么在html中使用url解析时需要加homeapp:home

urlpatterns = [
    path('', views.home, name='home'),
    path('js/', views.js, name='js'),
    path('archives/', views.archives, name='archives'),
    re_path(r'^archives/[0-9]{4}/[0-9]*', views.archives_by_year_month, name='archives_by_year_month'),
    # re_path(r'^archives/[0-9]{4}/[0-9]+/$', views.archives_by_month, name='archives_by_month'),


    path('categories/', views.categories, name='categories'),
    # 这个路由其实可以用正则来写,但是在单独逆向解析url怎么办
    re_path(r'^categories/.*?', views.category_detail, name='category_detail'),
    # path('categories/Algorithm/', views.algorithm, name='Algorithm'),
    # path('categories/Deep_Learning/', views.deep_learning, name='Deep Learning'),
    # path('categories/Django/', views.django, name='Django'),
    # path('categories/Face_Recognition/', views.face_recognition, name='Face Recognition'),
    # path('categories/Linux/', views.linux, name='Linux'),
    # path('categories/Machine_Learning/', views.machine_learning, name='Machine Learning'),
    # path('categories/Object_Detection/', views.object_detection, name='Object Detection'),
    # path('categories/Other/', views.other, name='Other'),
    # path('categories/Python/', views.python, name='Python'),
    path('tags/', views.tags, name='tags'),
    re_path(r'^tags/.*?', views.tag_detail, name='tag_detail'),
    path('about/', views.about, name='about'),
]

sharewithyou/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.static import static


from sharewithyou import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # namespace 主要是为了防止不同应用的路由name属性相同，在反向解析时无法解析，
    # 也可以不设置，只要保持name不同就行
    path('', include('homeapp.urls', namespace='homeapp')),
    path('', include('articlesapp.urls', namespace='articlesapp')),
    path('', include('userprofile.urls', namespace='userprofile')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('resourceapp.urls', namespace='resourceapp')),

    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
# url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT})

userprofile/urls.py
#!/usr/bin/python3.8
# -*- coding: UTF-8 -*-
"""
@author:Jaunezhou
@file:urls.py
@NAME:sharewithyou
@time:2021/12/22
@IDE: PyCharm
 
"""
from django.urls import path

from . import views
# from homeapp import views

app_name = 'userprofile'
# 如果这里加了app_name.
# 那么在html中使用url解析时需要加homeapp:home

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

templates/article/all_articles.html
{% extends 'base.html' %}
{% load static %}


{% block left_column %}
    <div class="column column-left is-4-tablet is-4-desktop is-4-widescreen  order-1">
        <div class="card widget" data-type="profile"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <nav class="level">
                    <div class="level-item has-text-centered flex-shrink-1">
                        <div>
                            <a href="{% url 'userprofile:login' %}">
                                <figure class="image is-128x180 mx-auto mb-2">
                                    <img class="avatar" src="{% static 'images/logos/logo.svg' %}"
                                         alt="PPOffice"></figure>
                            </a>
                            <p class="title is-size-4 is-block" style="line-height:inherit;">Week · Study</p>
                            <p class="is-size-6 is-block">Developer</p>
                            <p class="is-size-6 is-flex justify-content-center"><i
                                    class="fas fa-map-marker-alt mr-1"></i><span>Earth, Solar System</span></p></div>
                    </div>
                </nav>
                <nav class="level is-mobile">
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Posts</p><a href="{% url 'homeapp:archives' %}">
                            <p class="title"> {{ num }}</p>
                        </a></div>
                    </div>
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Categories</p><a href="{% url 'homeapp:categories' %}">
                            <p class="title">{{ cate_num }}</p></a></div>
                    </div>
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Tags</p><a href="{% url 'homeapp:tags' %}">
                            <p class="title">{{ tags_num }}</p></a>
                        </div>
                    </div>
                </nav>
                {% include 'connectblock.html' %}
            </div>
        </div>
        {% include 'linksblock.html' %}
         <div class="card widget" data-type="categories"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <div class="menu"><h3 class="menu-label">Categories</h3>
                    <ul class="menu-list">
                        {% for tmp_col,tmp_art in cate_articles.items %}
                        <li><a class="level is-mobile" href="/categories/{{ tmp_art.2 }}"><span
                                class="level-start"><span class="level-item">{{ tmp_col }}</span></span><span
                                class="level-end"><span class="level-item tag">{{ tmp_art.1 }}</span></span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {# 在移动端使用的样式#}
{#        {% include 'unkownblock.html' %}#}
    </div>
{% endblock left_column %}

{% block mid_column %}
    <div class="column order-2 column-main is-8-tablet is-8-desktop is-8-widescreen">

        {% if articles %}
            {% if search  %}
                <div>
                    <h1 class="title is-1 is-size-4-mobile">''{{ search }}''的搜索结果如下：</h1>
                </div>
            {% endif %}
            {% for article in articles %}
                <div class="card"
                     style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
                    <div class="card-image">
                        {% if article.avatar_svg %}
                            <a class="image is-7by3" href="{% url 'articlesapp:show_article' article.title %}" >
                                 <img class="fill" src="{{article.avatar_svg.url}}"
                                     alt="{{ article.title }}">
                        {% endif %}

                        </a>
                    </div>

                    <article class="card-content article" role="article">
                        <h1 class="title is-3 is-size-4-mobile">
                            <a class="link-muted"
                               href="{% url 'articlesapp:show_article' article.title %}">{{ article.title }}</a>
                        </h1>
                        <div class="article-meta is-size-7 is-uppercase level is-mobile">
                            <div class="level-left">
                                <span class="level-item fas fa-user">&nbsp;{{ article.author }}</span>
                                <span class=" level-item fas fa-clock">&nbsp;{{ article.created|date:"Y-m-d" }}</span>
                                <span class="level-item fas fa-comments">&nbsp;{{ article.comments.count }}</span>
                                <span class=" level-item fas fa-eye">&nbsp;{{ article.total_views }}</span>

                            </div>
                        </div>
                        <div class="article-meta is-size-7 is-uppercase level is-mobile">
                            <div class="level-left">
                                <span class="level-item">Category:{{ article.column }}</span>
                            </div>
                        </div>
                        <div class="article-meta is-size-7 is-uppercase level is-mobile">
                            <div class="level-left">
                                <span>tags:
                                    {% for tag in article.tags.all %}
                                        <a href="{% url 'articlesapp:articles' %}"
                                           class="badge badge-secondary">{{ tag }}, </a>
                                    {% endfor %}
                                </span>
                            </div>
                        </div>
                        <div class="content"><p>{{ article.body|safe}}</p></div>

                        <a class="article-more button is-small is-size-7"
                           href="{% url 'articlesapp:show_article' article.title %}"> Read More</a>
                    </article>
                </div>
            {% endfor %}
            <nav class="pagination" role="navigation" aria-label="pagination"
                 style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
                {% if articles.has_previous %}
                    <div class="pagination-previous">
                        <a href="?page={{ articles.previous_page_number }}">Previous</a>
                    </div>
                {% endif %}
                {% if articles.has_next %}
                    <div class="pagination-next"><a href="?page={{ articles.next_page_number }}">Next</a>
                    </div>
                {% endif %}
                {% if page_num != 1 %}
                    <ul class="pagination-list is-hidden-mobile">
                        {% for item in articles.paginator.page_range %}
                            {% if item == articles.number %}
                                <li><a class="pagination-link is-current" href="?page={{ articles.number }}">{{ articles.number }}</a></li>
                            {% else %}
                                <li><a class="pagination-link" href="?page={{ item }}">{{ item }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </nav>
        {% else %}
            <div>
                <h1 class="title is-1 is-size-4-mobile">暂无"{{ search }}"有关的文章，请换关键词检索。</h1>
            </div>
        {% endif %}
    </div>
{% endblock mid_column %}


{% block footer %}
    {% include 'footer.html' %}
{% endblock footer %}

{% block search %}
    <div class="searchbox">
        <div class="searchbox-container">
            <div class="searchbox-header">
                <div class="searchbox-input-container">
                    <form method="get" >
                        <input class="searchbox-input" name="search" type="text" placeholder="Type something..." >
                    </form>
                </div>
                <a class="searchbox-close" href="javascript:;">×</a></div>
                <div class="searchbox-body">
                    <section class="searchbox-result-section">
                        <header>Posts</header>
                        {% for article in article_list|slice:":5" %}
                        <a class="searchbox-result-item"
                           href="{% url 'articlesapp:show_article' article.title %}">
                            <span class="searchbox-result-icon"> <i class="fa fa-file"></i></span>
                            <span class="searchbox-result-content">
                                <span class="searchbox-result-title"> {{ article.title }}</span>
                                <span class="searchbox-result-title">AUTHOR: {{ article.author|upper }}&nbsp;&nbsp;
                                    POSTED:{{ article.created|date:"Y-m-d" }}</span>
                                <span class="searchbox-result-preview">{{ article.body|safe|slice:'100' }}</span>
                            </span>
                        </a>

                        {% endfor %}
                    </section>

                    <section class="searchbox-result-section">
                        <header>Categories</header>
                         {% for cate_key, article_info in  cate_articles.items %}
                            <a class="searchbox-result-item" href="/categories/{{ article_info.2 }}">
                                <span class="searchbox-result-icon"><i class="fa fa-folder"></i></span>
                                    <span class="searchbox-result-content">
                                        <span class="searchbox-result-title">{{ cate_key }}</span>
                                    </span>
                            </a>
                         {% endfor %}
                    </section>
                    <section class="searchbox-result-section">
                        <header>Tags</header>
                        {% for tag_name,article_info in tags_articles.items %}
                            <a class="searchbox-result-item" href="/tags/{{ tag_name }}">
                                <span class="searchbox-result-icon"><i class="fa fa-tag"></i></span>
                                <span class="searchbox-result-content">
                                    <span class="searchbox-result-title">{{ tag_name }}
                                    </span>
                                </span>
                            </a>
                        {% endfor %}
                    </section>
                </div>
            </div>
        </div>
    </div>
{% endblock search %}

templates/article/create.html
{% extends 'base.html' %}
{% load static %}

{% block left_column %}
    <div class="column column-left is-4-tablet is-4-desktop is-4-widescreen  order-1">
        <div class="card widget" data-type="profile"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <nav class="level">
                    <div class="level-item has-text-centered flex-shrink-1">
                        <div>
                            <a href="{% url 'userprofile:login' %}">
                                <figure class="image is-128x180 mx-auto mb-2">
                                    <img class="avatar" src="{% static 'images/logos/logo.svg' %}"
                                         alt="PPOffice"></figure>
                            </a>
                            <p class="title is-size-4 is-block" style="line-height:inherit;">Week · Study</p>
                            <p class="is-size-6 is-block">Developer</p>
                            <p class="is-size-6 is-flex justify-content-center"><i
                                    class="fas fa-map-marker-alt mr-1"></i><span>Earth, Solar System</span></p></div>
                    </div>
                </nav>
                <nav class="level is-mobile">
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Posts</p><a href="{% url 'homeapp:archives' %}">
                            <p class="title"> {{ num }}</p>
                            </a>
                        </div>
                    </div>

                    <div class="level-item has-text-centered is-marginless">
                    <div><p class="heading">Categories</p><a href="{% url 'homeapp:categories' %}">
                        <p class="title">{{ cate_num }}</p></a>
                    </div>
                </div>
                    <div class="level-item has-text-centered is-marginless">
                    <div><p class="heading">Tags</p><a href="{% url 'homeapp:tags' %}">
                        <p class="title">{{ tags_num }}</p></a>
                    </div>
                </div>
                </nav>
                {% include 'connectblock.html' %}
            </div>
        </div>
        {% include 'linksblock.html' %}

         <div class="card widget" data-type="categories"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <div class="menu"><h3 class="menu-label">Categories</h3>
                    <ul class="menu-list">
                        {% for tmp_col,tmp_art in cate_articles.items %}
                        <li>
                            <a class="level is-mobile" href="/categories/{{ tmp_art.2 }}">
                                <span class="level-start">
                                    <span class="level-item">{{ tmp_col }}</span>
                                </span>
                                <span class="level-end">
                                    <span class="level-item tag">{{ tmp_art.1 }}</span>
                                </span>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {# 在移动端使用的样式#}
{#        {% include 'unkownblock.html' %}#}
    </div>
{% endblock left_column %}


{% block mid_column %}

    <div class="column order-2 column-main is-8-tablet is-8-desktop is-8-widescreen">
        <form method="post" action="." enctype="multipart/form-data">
            <!-- Django中需要POST数据的地方都必须有csrf_token -->
            <!-- 记得增加 enctype ！ -->
            {% csrf_token %}
            <!-- 文章标题图 -->
{#            <link rel="stylesheet" type="text/css" href="{% static 'css-theme/white/bootstrap.min.css' %}">#}
            <link rel="stylesheet" type="text/css" href="{% static 'modify_css.css' %}">
            <div class="form-group">

                <div><label style="margin-top: 5px" for="avatar_svg">封面图</label></div>
                <input type="file" class="form-control-file" name="avatar_svg" id="avatar_svg">
            </div>

            <!-- 文章标题 -->
            <div class="form-group">
                <!-- 标签 -->
                <label for="title">文章标题</label>
                <!-- 文本框 -->
                <input type="text" class="form-control" id="title" name="title">
            </div>
            <!-- 文章栏目 -->
            <div class="form-group">
                <label for="column">类别</label>
                <select class="form-control" id="column" name="column">
                    <option value="none">Choose Category...</option>
                    {% for column in columns %}
                        <option value="{{ column.id }}">{{ column }}</option>
                    {% endfor %}
                </select>
            </div>
            <!-- 文章标签 -->
            <div class="form-group">
                <label for="tags">Tags</label>
                <input type="text" class="form-control col-3" id="tags" name="tags">
            </div>
            <!-- 文章正文 -->
            <div class="form-group">
                <label for="body">文章正文</label>
                <!-- 文本区域 -->
                <textarea type="text" class="form-control" id="body" name="body" rows="20" placeholder="仅支持markdown格式编辑"></textarea>
            </div>
            <!-- 提交按钮 -->
            <button type="submit" class="btn btn-primary">完成</button>
        </form>
    </div>

{% endblock mid_column %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock footer %}

{% block search %}
    <div class="searchbox">
        <div class="searchbox-container">
            <div class="searchbox-header">
                <div class="searchbox-input-container">
                    <form method="get" >
                        <input class="searchbox-input" name="search" type="text" placeholder="Type something..." >
                    </form>
                </div>
                <a class="searchbox-close" href="javascript:;">×</a></div>
                <div class="searchbox-body">
                    <section class="searchbox-result-section">
                        <header>Posts</header>
                        {% for article in article_list|slice:":5" %}
                        <a class="searchbox-result-item"
                           href="{% url 'articlesapp:show_article' article.id%}">
                            <span class="searchbox-result-icon"> <i class="fa fa-file"></i></span>
                            <span class="searchbox-result-content">
                                <span class="searchbox-result-title"> {{ article.title }}</span>
                                <span class="searchbox-result-title">AUTHOR: {{ item.author|upper }}&nbsp;&nbsp;
                                    POSTED:{{ item.created|date:"Y-m-d" }}</span>
                                <span class="searchbox-result-preview">{{ article.body|slice:'100' }}</span>
                            </span>
                        </a>
                        {% endfor %}


                    </section>
                    <section class="searchbox-result-section">
                        <header>Pages</header>
                        <a class="searchbox-result-item" href="{% url 'homeapp:home' %}">
                            <span class="searchbox-result-icon"><i class="fa fa-file"></i></span>
                            <span class="searchbox-result-content">
                                <span class="searchbox-result-title">(Untitled)</span>
                                <span class="searchbox-result-preview">A simple, delicate, and modern theme for Blog. Preview | Documentation | D</span>
                            </span>
                        </a>
                    </section>

                    <section class="searchbox-result-section">
                        <header>Categories</header>
                         {% for cate_key, article_info in  cate_articles.items %}
                            <a class="searchbox-result-item" href="/categories/{{ article_info.2 }}">
                                <span class="searchbox-result-icon"><i class="fa fa-folder"></i></span>
                                    <span class="searchbox-result-content">
                                        <span class="searchbox-result-title">{{ cate_key }}</span>
                                    </span>
                            </a>
                         {% endfor %}
                    </section>

                    <section class="searchbox-result-section">
                        <header>Tags</header>
                        {% for tag_name,article_info in tags_articles.items %}
                            <a class="searchbox-result-item" href="/tags/{{ tag_name }}">
                                <span class="searchbox-result-icon"><i class="fa fa-tag"></i></span>
                                <span class="searchbox-result-content">
                                    <span class="searchbox-result-title">{{ tag_name }}
                                    </span>
                                </span>
                            </a>
                        {% endfor %}
                    </section>

                </div>
            </div>
        </div>
    </div>
{% endblock search %}

templates/article/update.html
{% extends 'base.html' %}
{% load static %}

{% block left_column %}
    <div class="column column-left is-4-tablet is-4-desktop is-4-widescreen  order-1">
        <div class="card widget" data-type="profile"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <nav class="level">
                    <div class="level-item has-text-centered flex-shrink-1">
                        <div>
                            <a href="{% url 'userprofile:login' %}">
                                <figure class="image is-128x180 mx-auto mb-2">
                                    <img class="avatar" src="{% static 'images/logos/logo.svg' %}"
                                         alt="PPOffice"></figure>
                            </a>
                            <p class="title is-size-4 is-block" style="line-height:inherit;">Week · Study</p>
                            <p class="is-size-6 is-block">Developer</p>
                            <p class="is-size-6 is-flex justify-content-center"><i
                                    class="fas fa-map-marker-alt mr-1"></i><span>Earth, Solar System</span></p></div>
                    </div>
                </nav>
                <nav class="level is-mobile">
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Posts</p><a href="{% url 'homeapp:archives' %}"><p class="title">
                            {{ total }}</p>
                        </a></div>
                    </div>
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Categories</p><a href="{% url 'homeapp:categories' %}"><p class="title">
                            9</p></a></div>
                    </div>
                    <div class="level-item has-text-centered is-marginless">
                        <div><p class="heading">Tags</p><a href="{% url 'homeapp:tags' %}"><p class="title">4</p></a>
                        </div>
                    </div>
                </nav>
                {% include 'connectblock.html' %}
            </div>
        </div>
        {% include 'linksblock.html' %}
        <div class="card widget" data-type="categories"
             style="transition: opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s; opacity: 1; transform-origin: center top;">
            <div class="card-content">
                <div class="menu"><h3 class="menu-label">Categories</h3>
                    <ul class="menu-list">
                        {% for tmp_col,tmp_art in cate_articles.items %}
                        <li><a class="level is-mobile" href="/categories/{{ tmp_art.2 }}"><span
                                class="level-start"><span class="level-item">{{ tmp_col }}</span></span><span
                                class="level-end"><span class="level-item tag">{{ tmp_art.1 }}</span></span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {# 在移动端使用的样式#}
{#       todo tags {% include 'unkownblock.html' %}#}


    </div>
{% endblock left_column %}

{% block mid_column %}

    <div class="column order-2 column-main is-8-tablet is-8-desktop is-8-widescreen">

        <form method="post" action="." enctype="multipart/form-data">
            <!-- Django中需要POST数据的地方都必须有csrf_token -->
            {% csrf_token %}
            <!-- 文章标题图 -->
            <div class="form-group">
                {% if article.avatar_svg %}
{#                    <label for="avatar_svg">标题图</label><br>#}
                    <div class="card-image"><span class="image is-7by3">
                         <img  class="fill" src="{{ article.avatar_svg.url }}" alt="{{ article.title }}"></span>
                    </div>

                {% else %}
                    <label for="avatar_svg">当前文章无标题图</label>
                {% endif %}
                    <br>
                    <input type="file" class="form-control-file" name="avatar_svg" id="avatar_svg">
            </div>

            <!-- 文章标题 -->
{#            <link rel="stylesheet" type="text/css" href="{% static 'css-theme/white/bootstrap.min.css' %}">#}
            <link rel="stylesheet" type="text/css" href="{% static 'css-theme/white/article/create.css' %}">
            <div class="form-group" style="margin-bottom: 15px">
                <!-- 标签 -->
                <label for="title">文章标题</label>
                <!-- 文本框 -->
                <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
            </div>
            <!-- 文章栏目 -->
            <div class="form-group">
                <label for="column">栏目</label>
                <select class="form-control" id="column" name="column" >
                    <option value="none">请选择栏目..</option>
                    {% for column in columns %}
                        <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                selected
                                {% endif %} >
                            {{ column }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <!-- 文章标签-->
            <div class="form-group">
                <label for="tags">标签</label>
                <input type="text" class="form-control col-3" id="tags" name="tags"
                       value="{{ tags }}">
            </div>

            <!-- 文章正文 -->
            <div class="form-group">
                <label for="body">文章正文</label>
                <!-- 文本区域 -->
                <textarea type="text" class="form-control" id="body" name="body" rows="20">{{ article.body }}</textarea>
            </div>
            <!-- 提交按钮 -->
            <button type="submit" class="btn btn-primary">完成</button>
        </form>
    </div>

{% endblock mid_column %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock footer %}